- name: Remove neovim
  shell: rm -rf "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 8"
  tags:
    - install
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 1
  apt: name=luarocks
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 2 luacheck
  shell: luarocks install luacheck
  tags:
    - install
    - neovim

- name: Install LunarVim
  shell: LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)
  tags:
    - install
    - lunarvim
